In [1]:
import pandas as pd
import numpy as np

### Loading the data...

In [2]:
df_train = pd.read_csv("/home/anagha/dsr_group_project/dengu_prediction/data/dengue_features_train.csv")
df_train.head()

,city,year,weekofyear,week_start_date,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,...,reanalysis_precip_amt_kg_per_m2,reanalysis_relative_humidity_percent,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm
0,sj,1990,18,1990-04-30,0.122600,0.103725,0.198483,0.177617,12.42,297.572857,...,32.00,73.365714,12.42,14.012857,2.628571,25.442857,6.900000,29.4,20.0,16.0
1,sj,1990,19,1990-05-07,0.169900,0.142175,0.162357,0.155486,22.82,298.211429,...,17.94,77.368571,22.82,15.372857,2.371429,26.714286,6.371429,31.7,22.2,8.6
2,sj,1990,20,1990-05-14,0.032250,0.172967,0.157200,0.170843,34.54,298.781429,...,26.10,82.052857,34.54,16.848571,2.300000,26.714286,6.485714,32.2,22.8,41.4
3,sj,1990,21,1990-05-21,0.128633,0.245067,0.227557,0.235886,15.36,298.987143,...,13.90,80.337143,15.36,16.672857,2.428571,27.471429,6.771429,33.3,23.3,4.0
4,sj,1990,22,1990-05-28,0.196200,0.262200,0.251200,0.247340,7.52,299.518571,...,12.20,80.460000,7.52,17.210000,3.014286,28.942857,9.371429,35.0,23.9,5.8

In [4]:
df_train.shape

(1456, 24)

In [5]:
df_labels = pd.read_csv("/home/anagha/dsr_group_project/dengu_prediction/data/dengue_labels_train.csv")
df_labels

     city  year  weekofyear  total_cases
0      sj  1990          18            4
1      sj  1990          19            5
2      sj  1990          20            4
3      sj  1990          21            3
4      sj  1990          22            6
...   ...   ...         ...          ...
1451   iq  2010          21            5
1452   iq  2010          22            8
1453   iq  2010          23            1
1454   iq  2010          24            1
1455   iq  2010          25            4

[1456 rows x 4 columns]

In [6]:
df_labels.shape

(1456, 4)

In [7]:
df_merged = df_train.merge(df_labels, on=['city', 'year', 'weekofyear'])
df_merged['type'] = 'train'
df_merged

,city,year,weekofyear,week_start_date,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,...,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm,total_cases,type
0,sj,1990,18,1990-04-30,0.122600,0.103725,0.198483,0.177617,12.42,297.572857,...,12.42,14.012857,2.628571,25.442857,6.900000,29.4,20.0,16.0,4,train
1,sj,1990,19,1990-05-07,0.169900,0.142175,0.162357,0.155486,22.82,298.211429,...,22.82,15.372857,2.371429,26.714286,6.371429,31.7,22.2,8.6,5,train
2,sj,1990,20,1990-05-14,0.032250,0.172967,0.157200,0.170843,34.54,298.781429,...,34.54,16.848571,2.300000,26.714286,6.485714,32.2,22.8,41.4,4,train
3,sj,1990,21,1990-05-21,0.128633,0.245067,0.227557,0.235886,15.36,298.987143,...,15.36,16.672857,2.428571,27.471429,6.771429,33.3,23.3,4.0,3,train
4,sj,1990,22,1990-05-28,0.196200,0.262200,0.251200,0.247340,7.52,299.518571,...,7.52,17.210000,3.014286,28.942857,9.371429,35.0,23.9,5.8,6,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1451,iq,2010,21,2010-05-28,0.342750,0.318900,0.256343,0.292514,55.30,299.334286,...,55.30,18.485714,9.800000,28.633333,11.933333,35.4,22.4,27.0,5,train
1452,iq,2010,22,2010-06-04,0.160157,0.160371,0.136043,0.225657,86.47,298.330000,...,86.47,18.070000,7.471429,27.433333,10.500000,34.7,21.7,36.6,8,train
1453,iq,2010,23,2010-06-11,0.247057,0.146057,0.250357,0.233714,58.94,296.598571,...,58.94,17.008571,7.500000,24.400000,6.900000,32.2,19.2,7.4,1,train
1454,iq,2010,24,2010-06-18,0.333914,0.245771,0.278886,0.325486,59.67,296.345714,...,59.67,16.815714,7.871429,25.433333,8.733333,31.2,21.0,16.0,1,train
1455,iq,2010,25,2010-06-25,0.298186,0.232971,0.274214,0.315757,63.22,298.097143,...,63.22,17.355714,11.014286,27.475000,9.900000,33.7,22.2,20.4,4,train

In [9]:
df_test = pd.read_csv("data/dengue_features_test.csv")
df_test['type'] = 'test'
df_test

,city,year,weekofyear,week_start_date,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,...,reanalysis_relative_humidity_percent,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm,type
0,sj,2008,18,2008-04-29,-0.018900,-0.018900,0.102729,0.091200,78.60,298.492857,...,78.781429,78.60,15.918571,3.128571,26.528571,7.057143,33.3,21.7,75.2,test
1,sj,2008,19,2008-05-06,-0.018000,-0.012400,0.082043,0.072314,12.56,298.475714,...,78.230000,12.56,15.791429,2.571429,26.071429,5.557143,30.0,22.2,34.3,test
2,sj,2008,20,2008-05-13,-0.001500,NaN,0.151083,0.091529,3.66,299.455714,...,78.270000,3.66,16.674286,4.428571,27.928571,7.785714,32.8,22.8,3.0,test
3,sj,2008,21,2008-05-20,NaN,-0.019867,0.124329,0.125686,0.00,299.690000,...,73.015714,0.00,15.775714,4.342857,28.057143,6.271429,33.3,24.4,0.3,test
4,sj,2008,22,2008-05-27,0.056800,0.039833,0.062267,0.075914,0.76,299.780000,...,74.084286,0.76,16.137143,3.542857,27.614286,7.085714,33.3,23.3,84.1,test
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411,iq,2013,22,2013-05-28,0.301471,0.380029,0.280629,0.383186,41.12,297.774286,...,89.990000,41.12,17.185714,10.100000,27.400000,9.050000,32.6,21.8,33.0,test
412,iq,2013,23,2013-06-04,0.247600,0.296343,0.285371,0.350357,71.52,297.167143,...,93.891429,71.52,17.448571,9.657143,27.520000,10.720000,33.8,21.4,68.0,test
413,iq,2013,24,2013-06-11,0.238729,0.251029,0.252586,0.249771,78.96,295.831429,...,94.967143,78.96,16.410000,7.385714,27.200000,10.075000,32.6,21.6,93.2,test
414,iq,2013,25,2013-06-18,0.310429,0.302700,0.406614,0.403943,39.54,295.778571,...,89.057143,39.54,15.137143,8.228571,26.700000,8.480000,32.2,21.8,34.1,test
415,iq,2013,26,2013-06-25,0.339467,0.240071,0.356943,0.273600,51.80,297.372857,...,87.030000,51.80,16.148571,11.542857,27.350000,9.675000,32.6,22.0,14.9,test

In [14]:
df_final = pd.concat([df_merged, df_test], ignore_index=True)
df_final

,city,year,weekofyear,week_start_date,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,...,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm,total_cases,type
0,sj,1990,18,1990-04-30,0.122600,0.103725,0.198483,0.177617,12.42,297.572857,...,12.42,14.012857,2.628571,25.442857,6.900000,29.4,20.0,16.0,4.0,train
1,sj,1990,19,1990-05-07,0.169900,0.142175,0.162357,0.155486,22.82,298.211429,...,22.82,15.372857,2.371429,26.714286,6.371429,31.7,22.2,8.6,5.0,train
2,sj,1990,20,1990-05-14,0.032250,0.172967,0.157200,0.170843,34.54,298.781429,...,34.54,16.848571,2.300000,26.714286,6.485714,32.2,22.8,41.4,4.0,train
3,sj,1990,21,1990-05-21,0.128633,0.245067,0.227557,0.235886,15.36,298.987143,...,15.36,16.672857,2.428571,27.471429,6.771429,33.3,23.3,4.0,3.0,train
4,sj,1990,22,1990-05-28,0.196200,0.262200,0.251200,0.247340,7.52,299.518571,...,7.52,17.210000,3.014286,28.942857,9.371429,35.0,23.9,5.8,6.0,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1867,iq,2013,22,2013-05-28,0.301471,0.380029,0.280629,0.383186,41.12,297.774286,...,41.12,17.185714,10.100000,27.400000,9.050000,32.6,21.8,33.0,NaN,test
1868,iq,2013,23,2013-06-04,0.247600,0.296343,0.285371,0.350357,71.52,297.167143,...,71.52,17.448571,9.657143,27.520000,10.720000,33.8,21.4,68.0,NaN,test
1869,iq,2013,24,2013-06-11,0.238729,0.251029,0.252586,0.249771,78.96,295.831429,...,78.96,16.410000,7.385714,27.200000,10.075000,32.6,21.6,93.2,NaN,test
1870,iq,2013,25,2013-06-18,0.310429,0.302700,0.406614,0.403943,39.54,295.778571,...,39.54,15.137143,8.228571,26.700000,8.480000,32.2,21.8,34.1,NaN,test
1871,iq,2013,26,2013-06-25,0.339467,0.240071,0.356943,0.273600,51.80,297.372857,...,51.80,16.148571,11.542857,27.350000,9.675000,32.6,22.0,14.9,NaN,test

In [15]:
df_final.describe()

,year,weekofyear,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,reanalysis_avg_temp_k,reanalysis_dew_point_temp_k,...,reanalysis_relative_humidity_percent,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm,total_cases
count,1872.000000,1872.000000,1635.000000,1809.000000,1849.000000,1849.000000,1857.000000,1860.000000,1860.000000,1860.000000,...,1860.000000,1857.000000,1860.000000,1860.000000,1817.000000,1817.000000,1849.000000,1849.000000,1845.000000,1456.000000
mean,2003.194979,26.489316,0.138588,0.129713,0.204663,0.202174,44.109278,298.727770,299.253955,295.284823,...,82.237158,44.109278,16.786638,4.952903,27.226651,8.004112,32.470795,22.160790,38.201897,24.675137
std,6.292268,15.006319,0.146413,0.125082,0.075064,0.085768,42.065868,1.387410,1.272510,1.528046,...,7.203803,42.065868,1.547336,3.545887,1.281254,2.205734,1.950483,1.613325,44.961360,43.596000
min,1990.000000,1.000000,-0.463400,-0.456100,-0.015533,-0.063457,0.000000,294.554286,294.892857,289.642857,...,57.787143,0.000000,11.715714,1.357143,21.400000,4.042857,26.700000,14.200000,0.000000,0.000000
25%,1999.000000,13.750000,0.035300,0.041225,0.153457,0.141014,9.430000,297.678929,298.276786,294.164643,...,77.214643,9.430000,15.590714,2.357143,26.328571,6.357143,31.100000,21.100000,8.800000,5.000000
50%,2004.000000,26.000000,0.127317,0.115200,0.197029,0.188229,36.640000,298.617143,299.300000,295.667143,...,80.307143,36.640000,17.137143,2.871429,27.433333,7.200000,32.800000,22.200000,23.800000,12.000000
75%,2008.000000,39.000000,0.252225,0.223360,0.250857,0.248086,67.500000,299.891429,300.271429,296.502857,...,86.799286,67.500000,18.028929,7.757143,28.200000,9.625000,33.900000,23.300000,51.500000,28.000000
max,2013.000000,53.000000,0.508357,0.649000,0.538314,0.546017,390.600000,302.200000,303.328571,298.450000,...,98.610000,390.600000,20.461429,16.028571,30.800000,15.800000,42.200000,26.700000,543.300000,461.000000

In [16]:
df_final = df_final.drop('week_start_date', axis=1)
df_final.dtypes

city                                      object
year                                       int64
weekofyear                                 int64
ndvi_ne                                  float64
ndvi_nw                                  float64
ndvi_se                                  float64
ndvi_sw                                  float64
precipitation_amt_mm                     float64
reanalysis_air_temp_k                    float64
reanalysis_avg_temp_k                    float64
reanalysis_dew_point_temp_k              float64
reanalysis_max_air_temp_k                float64
reanalysis_min_air_temp_k                float64
reanalysis_precip_amt_kg_per_m2          float64
reanalysis_relative_humidity_percent     float64
reanalysis_sat_precip_amt_mm             float64
reanalysis_specific_humidity_g_per_kg    float64
reanalysis_tdtr_k                        float64
station_avg_temp_c                       float64
station_diur_temp_rng_c                  float64
station_max_temp_c                       float64
station_min_temp_c                       float64
station_precip_mm                        float64
total_cases                              float64
type                                      object
dtype: object

#### Encoding categorical values

In [17]:
df_final['city'] = df_final['city'].map({'sj': 0, 'iq': 1})

#### Replacing missing values with null

In [ ]:
cols_with_nulls = df_final.isnull().sum()[df_final.isnull().sum() > 0].index.tolist()
cols_with_nulls = [col for col in cols_with_nulls if col != 'total_cases']
#df_final[cols_with_nulls] = df_final[cols_with_nulls].fillna(df_final[cols_with_nulls].mean())

In [ ]:
train_df = df_final[df_final['type'] == 'train']
test_df  = df_final[df_final['type'] == 'test']

# Calculate mean from train only
train_mean = train_df[cols_with_nulls].mean()

# Fill both using train mean
train_df[cols_with_nulls] = train_df[cols_with_nulls].fillna(train_mean)
test_df[cols_with_nulls]  = test_df[cols_with_nulls].fillna(train_mean)

# Recombine
df_final = pd.concat([train_df, test_df], ignore_index=True)

In [32]:
# Split by city
df_sj = df_final[df_final['city'] == 0]
df_iq = df_final[df_final['city'] == 1]

# Split by type for each city
train_sj = df_sj[df_sj['type'] == 'train']
test_sj  = df_sj[df_sj['type'] == 'test']

train_iq = df_iq[df_iq['type'] == 'train']
test_iq  = df_iq[df_iq['type'] == 'test']

# Features and target
features = [col for col in df_final.columns if col not in ['total_cases', 'type']]

X_train_sj = train_sj[features]
y_train_sj = train_sj['total_cases']

X_test_sj = test_sj[features]

X_train_iq = train_iq[features]
y_train_iq = train_iq['total_cases']

X_test_iq = test_iq[features]

In [33]:
print("SJ train:", X_train_sj.shape, "SJ test:", X_test_sj.shape)
print("IQ train:", X_train_iq.shape, "IQ test:", X_test_iq.shape)

SJ train: (936, 23) SJ test: (260, 23)
IQ train: (520, 23) IQ test: (156, 23)

In [36]:
from sklearn.ensemble import RandomForestRegressor

# Define models
rf_sj = RandomForestRegressor(n_estimators=100, random_state=42)
rf_iq = RandomForestRegressor(n_estimators=100, random_state=42)

# Fit
rf_sj.fit(X_train_sj, y_train_sj)
rf_iq.fit(X_train_iq, y_train_iq)

# Predict
pred_sj = rf_sj.predict(X_test_sj)
pred_iq = rf_iq.predict(X_test_iq)

# Round to nearest integer since cases are whole numbers
pred_sj = pred_sj.round().astype(int)
pred_iq = pred_iq.round().astype(int)

print("SJ predictions:", pred_sj[:5])
print("IQ predictions:", pred_iq[:5])

SJ predictions: [5 6 7 7 8]
IQ predictions: [3 3 6 3 4]

In [45]:
# Create prediction dataframes
pred_df_sj = test_sj[['city', 'year', 'weekofyear']].copy()
pred_df_sj['total_cases'] = pred_sj

pred_df_iq = test_iq[['city', 'year', 'weekofyear']].copy()
pred_df_iq['total_cases'] = pred_iq

# Concatenate sj first then iq
preds = pd.concat([pred_df_sj, pred_df_iq], ignore_index=True)

preds

     city  year  weekofyear  total_cases
0       0  2008          18            5
1       0  2008          19            6
2       0  2008          20            7
3       0  2008          21            7
4       0  2008          22            8
..    ...   ...         ...          ...
411     1  2013          22            7
412     1  2013          23            3
413     1  2013          24            2
414     1  2013          25            4
415     1  2013          26            3

[416 rows x 4 columns]

In [46]:
preds['city'] = preds['city'].map({0: 'sj', 1: 'iq'})
preds

    city  year  weekofyear  total_cases
0     sj  2008          18            5
1     sj  2008          19            6
2     sj  2008          20            7
3     sj  2008          21            7
4     sj  2008          22            8
..   ...   ...         ...          ...
411   iq  2013          22            7
412   iq  2013          23            3
413   iq  2013          24            2
414   iq  2013          25            4
415   iq  2013          26            3

[416 rows x 4 columns]

In [47]:
preds.to_csv('predictions.csv', index=False)

In [48]:
pd.read_csv('predictions.csv')

    city  year  weekofyear  total_cases
0     sj  2008          18            5
1     sj  2008          19            6
2     sj  2008          20            7
3     sj  2008          21            7
4     sj  2008          22            8
..   ...   ...         ...          ...
411   iq  2013          22            7
412   iq  2013          23            3
413   iq  2013          24            2
414   iq  2013          25            4
415   iq  2013          26            3

[416 rows x 4 columns]